### ISSUE TITLE
City/County boundaries in TN

### ISSUE THREAD

**Issue by rjhale1971** [rjhale1971/tn_ng911_data_model#23]
I need to do a trigger for the city/county boundaries in TN - similar to the ZCTA. I can get county boundaries from census.....not sure on city boundaries. I'll do some digging.

**Comment by KSnyderCode** [comment]
I believe the Cities should be under the County Subdivision layer from USCB.

**Comment by rjhale1971** [comment]
Cool - I figure this will make things a little more brain dead. Drop a point and it gets the City/County. For Henry I just hard coded everything by zip. A city got a certain zip. Anyway - yay progress.

**Comment by KSnyderCode** [comment]
Yup.  Get a nice ST_Intersects going on there for the layer.

**Comment by KSnyderCode** [comment]
As it turns out that TN's County Subdivision is the counties broken down into corresponding districts. Places is the layer from TIGER/LINE that we want to get the city boundaries.  I'm assuming if a point DOESN'T intersect a city boundary are we calling it unincorporated area?
